language: r
cache: packages
sudo: false
warnings_are_errors: false

install:
  - Rscript install-packages.R
  
script:
  - R -e 'setwd("testthat"); testthat::test_dir("../testthat")'
  - R -e 'setwd("./DataCleaningScripts"); source("new_weather_data.R"); append_weather()'
  - R -e 'setwd("./DataCleaningScripts"); source("update_portal_rodent_trapping.r"); writetrappingtable()'
  - R -e 'setwd("./DataCleaningScripts"); source("update_portal_plots.R"); writeportalplots()'
  - R -e 'setwd("./DataCleaningScripts"); source("new_moon_numbers.r"); writenewmoons()'
  - R -e 'setwd("./DataCleaningScripts"); source("update_portal_plant_censuses.R"); writecensustable()'
after_success:
  - bash update_repo.sh
