language: r
cache: packages
sudo: false
warnings_are_errors: false
git:
  depth: false
install:
  - Rscript install-packages.R
  
script:
  - Rscript update-data.R
  - Rscript testthat.R
  - Rscript archive.R

notifications:
  slack: weecology:CwWehNkftf60m2nc1LN7QMqx
    if: branch = master
  
after_success:
slack:
      on_success: never
      on_failure: always
