language: r
cache: packages
sudo: false
warnings_are_errors: false
git:
  depth: false
  
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - gdal-bin 
      - libproj-dev 
      - proj-data 
      - proj-bin 
      - libgeos-dev
      - libv8-dev 
      - libprotobuf-dev 
      - protobuf-compiler 
      - libjq-dev

install:
  - Rscript install-packages.R
  
script:
  - Rscript update-data.R
  - Rscript testthat.R
  - Rscript archive.R

notifications:
  slack:
    rooms: weecology:CwWehNkftf60m2nc1LN7QMqx
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: always
